import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[shell]
program = "fish"
args = [ "-l", "-c tmux attach || tmux" ]

[font]
size = 13

[colors]
draw_bold_text_with_bright_colors = false
